### ISSUE TITLE
how do i use this

### ISSUE THREAD

**Issue by hygdyft54tfyuj** [UnsignedArduino/Arcade-MIDI-to-Song#1]

**Comment by UnsignedArduino** [comment]
It's a CLI Python project, but it isn't finished yet.

**Comment by hygdyft54tfyuj** [comment]
thanks, can you make a gui?

**Comment by UnsignedArduino** [comment]
I'm considering turning this project into a web page after it's done.

**Comment by hygdyft54tfyuj** [comment]
thanks

**Comment by hygdyft54tfyuj** [comment]
i still don't know the commands for the script.

**Comment by hygdyft54tfyuj** [comment]
please make it a website

**Comment by UnsignedArduino** [comment]
It isn't finished yet, so there is no point turning it into a website - you wouldn't be able to use it. 

I'm quite busy so this project is on the back burner :(

**Comment by hygdyft54tfyuj** [comment]
okay, i get it.
